services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app/
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8888
    ports:
      - 8888:8888
